# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180926_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='password',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
