# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-09-27 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_parent_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='home.Parent'),
            preserve_default=False,
        ),
    ]
