# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-05 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_child_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='face_code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
