# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 03:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20181023_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='profile_image',
            field=models.FileField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
