# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-26 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_child_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='profile_image',
            field=models.CharField(max_length=255),
        ),
    ]
