# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-11 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181026_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='profile_image',
            field=models.TextField(),
        ),
    ]
